services:
  orderservice.api:
    image: ${DOCKER_REGISTRY-}orderserviceapi
    build:
      context: .
      dockerfile: OrderService/OrderService.Api/Dockerfile

  customerservice.api:
    image: ${DOCKER_REGISTRY-}customerserviceapi
    build:
      context: .
      dockerfile: CustomerService/CustomerService.Api/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest

  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: GatewayAPI/Gateway.Api/Dockerfile

